version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${PMA_ACCESS_PORT}:80"
